import { NextRequest } from 'next/server';
import axios from 'axios';
import { POST } from '../src/app/api/translate/route';

jest.mock('next/server', () => ({
  NextRequest: jest.fn(),
  NextResponse: {
    json: jest.fn((data, init) => new Response(JSON.stringify(data), init)),
    error: jest.fn()
  }
}));

jest.mock('axios');
const mockedAxios = axios as jest.Mocked<typeof axios>;

describe('Translation API Endpoint', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env.AZURE_OPENAI_ENDPOINT = 'https://test-endpoint.azure.com';
    process.env.AZURE_OPENAI_API_KEY = 'test-api-key';
    process.env.AZURE_OPENAI_DEPLOYMENT_NAME = 'test-deployment';
    
    jest.clearAllMocks();
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  // Test Generated by Keploy
  describe('POST endpoint', () => {
    it('should successfully translate text', async () => {
      const requestData = {
        text: 'Hello world',
        sourceLang: 'en',
        targetLang: 'es'
      };

      const request = {
        json: jest.fn().mockResolvedValue(requestData)
      } as unknown as NextRequest;

      mockedAxios.post.mockResolvedValue({
        data: {
          choices: [{
            message: {
              content: 'Hola mundo'
            }
          }]
        }
      });

      const response = await POST(request);
      const responseData = await response.json();

      expect(responseData).toEqual({
        originalText: 'Hello world',
        translatedText: 'Hola mundo',
        sourceLang: 'en',
        targetLang: 'es'
      });
      
      expect(mockedAxios.post).toHaveBeenCalledWith(
        expect.stringContaining('/chat/completions'),
        expect.objectContaining({
          messages: expect.arrayContaining([
            expect.objectContaining({
              content: expect.stringContaining('Hello world')
            })
          ])
        }),
        expect.any(Object)
      );
    });

    it('should return 400 when required parameters are missing', async () => {
      const requestData = {
        text: 'Hello world',
      };

      const request = {
        json: jest.fn().mockResolvedValue(requestData)
      } as unknown as NextRequest;

      const response = await POST(request);
      expect(response.status).toBe(400);
      
      const responseData = await response.json();
      expect(responseData.error).toBe('Missing required parameters');
    });

    it('should return 500 when Azure configuration is missing', async () => {
      delete process.env.AZURE_OPENAI_ENDPOINT;
      
      const requestData = {
        text: 'Hello world',
        sourceLang: 'en',
        targetLang: 'es'
      };

      const request = {
        json: jest.fn().mockResolvedValue(requestData)
      } as unknown as NextRequest;

      const response = await POST(request);
      expect(response.status).toBe(500);
      
      const responseData = await response.json();
      expect(responseData.error).toBe('Missing Azure OpenAI configuration');
    });
  });
});